#!/usr/bin/env python

from distutils.core import setup

setup(
    name='pout2groups',
    version='0.1',
    description='A script to perform protein grouping on pout-files (generated by Percolator).',
    author='Pieter Verschaffelt',
    author_email='pieter.verschaffelt@ugent.be',
    packages=['pout2groups'],
    package_dir={'pout2groups': 'pout2groups'},
    entry_points={
        'console_scripts': ['pout2groups = pout2groups.main']
    }
)
