#!/usr/bin/env python

import setuptools
from distutils.core import setup

setup(
    name='pout2prot',
    version='0.1',
    description='A script to perform protein grouping on pout-files (generated by Percolator).',
    author='Pieter Verschaffelt',
    author_email='pieter.verschaffelt@ugent.be',
    packages=['pout2prot'],
    package_dir={'pout2prot': 'pout2prot'},
    entry_points={
        'console_scripts': ['pout2prot = pout2prot:main.main']
    }
)
